blank_issues_enabled: false
contact_links:
  - name: Atlas CLI Feature Request
    url: https://feedback.mongodb.com/?category=7556329857711623227
    about: Request a feature or up-vote an existing suggestion!
  - name: MongoDB Support
    url: https://support.mongodb.com/
    about: Support is provided under MongoDB Atlas or Enterprise Advance support plans.
  - name: MongoDB Atlas
    url: https://www.mongodb.com/cloud/atlas
    about: Learn more about MongoDB Atlas.
